name: Viper

services:
  postgres:
    build: ./db
    env_file: ./env/db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - /srv/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  viper:
    build: ./viper
    env_file: ./env/viper.env
    volumes:
      - /srv/viper-stamps:/srv/stamps
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  inngest:
    build: ./inngest
    env_file: ./env/inngest.env
    ports:
      - "8288:8288"
    entrypoint: ["/bin/sh", "-c"]
    command: ["inngest dev -u $$INNGEST_BOOTSTRAP_URL"]
    depends_on:
      - viper

  prisma-studio:
    build: ./viper
    env_file: ./env/viper.env
    ports:
      - "5555:5555"
    profiles:
      - dev
    command: sh -c "npx prisma studio --browser none"
    depends_on:
      postgres:
        condition: service_healthy